[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0Xfile:///home/Shinobid/Downloads/Se7en.1995.1080p.UHD.BluRay.x265.DD+5.1-Pahe.in12345.mkv)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc5\0\0\x1U\0\0\x5\x98\0\0\x2i\0\0\x3\xc5\0\0\x1U\0\0\x5\x98\0\0\x2i\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc5\0\0\x1U\0\0\x5\x98\0\0\x2i)

[FullScreen]
pos=@Point(560 1136)
screen=@Rect(0 0 1920 1200)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(468 203)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/Shinobid/Downloads/nFODuQr.mp4, file:///home/Shinobid/Downloads/assd.mp4, file:///home/Shinobid/Downloads/DASH_1080.mp4, file:///home/Shinobid/Downloads/SnapReels.Net_AQNRICmLp5sqHW_QxD3bjuTl0tbG7_iv7a0G3lGygNMcAKGj0zmZ32G4TNsvlYJ1t_6eHNLlJSZXycPwXlLr6zyy.mp4, file:///home/Shinobid/K/Entertainment/Movies/Howl%27s.Moving.Castle.2004.1080p.BluRay.x265.DD%2B5.1-Pahe.in.mkv, file:///home/Shinobid/K/Entertainment/Movies/Princess.Mononoke.1997.1080p.BluRay.x264.DD5.1-Pahe.in.mkv, file:///home/Shinobid/Downloads/Salvation%20%28ft.%20Forts%29%20%EF%BD%9C%20For%20Demacia%202026%20Season%201%20Cinematic%20-%20League%20of%20Legends.mp4, file:///home/Shinobid/K/Entertainment/Movies/Inglourious.Basterds.2009.1080p.UHD.BluRay.x265.10Bit.DD5.1-Pahe.in.mkv, file:///usr/share/sddm/themes/silent/backgrounds/o7dQQuI96xjqpHx_Space%20DreamScene%20Live%20Wallpaper.mp4, file:///usr/share/sddm/themes/silent/backgrounds/red.mp4, file:///usr/share/sddm/themes/silent/backgrounds/rei.mp4, file:///usr/share/sddm/themes/silent/backgrounds/rei2.mp4, file:///usr/share/sddm/themes/silent/backgrounds/silvia.mp4, file:///usr/share/sddm/themes/silent/backgrounds/animegirl.mp4, file:///usr/share/sddm/themes/silent/backgrounds/skull.mp4, file:///usr/share/sddm/themes/silent/backgrounds/ken.mp4, file:///home/Shinobid/Downloads/Se7en.1995.1080p.UHD.BluRay.x265.DD+5.1-Pahe.in12345.mkv, file:///home/Shinobid/Downloads/Se7en.1995.1080p.UHD.BluRay.x265.DD%2B5.1-Pahe.in12345.mkv
times=0, 17900, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
