[ProtonDrive]
type = protondrive
username = Karim.4Dev@protonmail.com
password = HyuQCbJuFs22eg4DtxMd4w4RxK66wk1BTvttKjYp
client_uid = gwl4vewcuc4uutzfse5cizqgx7awms4d
client_access_token = o454xdyijknxegutgdliinncln4p7aqf
client_refresh_token = wr66mj3t74zpkhwpkcsfieyb64vfri4h
client_salted_key_pass = ckI2UmV6dzkxb2ZqUzJqbXF6VmhsVjEzeld3LzVVcQ==

