[General]
AutostartChanged=true
ClientID=b3f7927b-9447-4ab9-b532-0953612130db
EventInstall=true
HandwriteBackground=0
LastUpdateCount=1
LastUpdateVersion=03.00.0147
SettingsVersion=1
SystemTrayAvailable=true
TutorialWasShown=true
UpdatePercent=95
userId=8a66ae50dca24c4ea5bb147ff7d97dfe
